name: Pull Request Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pr-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking (fast feedback)
        run: npm run type-check

      - name: Unit tests (fast feedback)
        run: npm test

      - name: Build verification
        run: npm run build

      - name: Verify build artifacts
        run: |
          echo "📦 Build Artifacts:"
          ls -la dist/
          echo "📄 HTML Entry Point:"
          head -5 dist/index.html
          echo "🔧 Service Worker:"
          ls -la dist/sw.js
          echo "📋 Web Manifest:"
          ls -la dist/manifest.webmanifest

      - name: ESLint (non-blocking)
        run: npm run lint || echo "⚠️ ESLint warnings found"
        continue-on-error: true

  draft-pr-checks:
    name: Draft PR Basic Checks
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type checking only (draft)
        run: npm run type-check

      - name: Build verification only (draft)
        run: npm run build

  pr-size-check:
    name: PR Size Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR size
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | wc -l)
          CHANGED_LINES=$(git diff --stat origin/main...HEAD | tail -n1 | grep -o '[0-9]* insertions' | grep -o '[0-9]*' || echo "0")

          echo "📊 PR Statistics:"
          echo "Files changed: $CHANGED_FILES"
          echo "Lines changed: $CHANGED_LINES"

          if [ "$CHANGED_FILES" -gt 50 ]; then
            echo "⚠️ Large PR: Consider breaking into smaller changes"
          fi

          if [ "$CHANGED_LINES" -gt 1000 ]; then
            echo "⚠️ Very large PR: Review complexity may be high"
          fi

  conventional-commits:
    name: Commit Message Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate commit messages
        run: npx commitlint --from=origin/main --to=HEAD --verbose
